### ISSUE TITLE
大佬请看一下bmap动态风流图demo

### ISSUE THREAD

**Issue by ssshem** [chengquan223/map-canvas#10]
我最近在研究那个earth.nullschool.net、windy.com那种动态风场，然后找到您这个项目了，但我发现在基于百度地图做的动态风流图baidu-map-wind.html这个demo中，有个问题我很奇怪，我删减样例数据只剩到10条，地图也是全图被渲染风场，或者我不删减，但不管怎么拖动，还是全图被渲染，看了代码，但实在看不懂，跟看earth.nullschool.net源码一样看不来。。果然我前端js很菜。。感谢大神这个项目

**Comment by chengquan223** [comment]
你好，样例数据是为了在插值中使用，它的多少只会影响该区域部分的风场的流向，与是否全图渲染并无关系，默认就是渲染整个屏幕的。

**Comment by ssshem** [comment]
@chengquan223  那这样的话不就不精确了吗，我想的是，如果数据是哪一块的那就渲染哪一块地图，不应该渲染整个地图吧

**Comment by chengquan223** [comment]
@ssshem 你说的这种情况得在渲染的时候判断生成的粒子是否在某一个区域范围内，在则渲染，否则跳过。

**Comment by acodercat** [comment]
请问有高德地图的风场demo吗？

**Comment by chengquan223** [comment]
> 请问有高德地图的风场demo吗？

没有，可以参考百度的风场demo整合

**Comment by acodercat** [comment]
> > 请问有高德地图的风场demo吗？
> 
> 没有，可以参考百度的风场demo整合

好麻烦

**Comment by Billy2536292424** [comment]
大佬，实在看不懂你的代码，能不能写一篇博客详细介绍一下你这个思路，简单介绍一下实现过程也可以啊

**Comment by Billy2536292424** [comment]
大佬，可以给一下你实现的思路吗，主要是插值那里为什么要遍历所有点然后算一个点的插值

**Comment by chengquan223** [comment]
我是对临近区域的每一个离散点平均运算，求最终x点的值




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Billy2536292424"<notifications@github.com&gt;; 
发送时间: 2019年11月22日(星期五) 下午5:00
收件人: "chengquan223/map-canvas"<map-canvas@noreply.github.com&gt;; 
抄送: "Jack、Chen"<309581454@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [chengquan223/map-canvas] 大佬请看一下bmap动态风流图demo (#10)




大佬，可以给一下你实现的思路吗，主要是插值那里为什么要遍历所有点然后算一个点的插值
 
&mdash;

**Comment by Billy2536292424** [comment]
谢谢大佬，不知道大佬有没有做过三维风场

**Comment by chengquan223** [comment]
这个没有哦------------------ 原始邮件 ------------------
发件人: "Billy2536292424"<notifications@github.com>
发送时间: 2019年11月22日(星期五) 晚上7:57
收件人: "chengquan223/map-canvas"<map-canvas@noreply.github.com>;
抄送: "JackChen"<309581454@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [chengquan223/map-canvas] 大佬请看一下bmap动态风流图demo (#10)



谢谢大佬，不知道大佬有没有做过三维风场
 
&mdash;

**Comment by Billy2536292424** [comment]
好的，再次感谢指点

**Comment by Billy2536292424** [comment]
大佬，我是做C++的现在有一个项目需要用JS做动态风场，看了您的例子之后对我启发很大，但是还是有部分内容有点不是很理解，方便加个微信吗，我想再向您请教一下，希望大佬不吝赐教

**Comment by chengquan223** [comment]
hrq674799262




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Billy2536292424"<notifications@github.com&gt;; 
发送时间: 2019年12月5日(星期四) 上午9:09
收件人: "chengquan223/map-canvas"<map-canvas@noreply.github.com&gt;; 
抄送: "Jack、Chen"<309581454@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [chengquan223/map-canvas] 大佬请看一下bmap动态风流图demo (#10)




大佬，我是做C++的现在有一个项目需要用JS做动态风场，看了您的例子之后对我启发很大，但是还是有部分内容有点不是很理解，方便加个微信吗，我想再向您请教一下，希望大佬不吝赐教
 
&mdash;
