### ISSUE TITLE
高德地图的demo move无效

### ISSUE THREAD

**Issue by SanMu9** [chengquan223/map-canvas#16]

**Comment by chengquan223** [comment]
> _No description provided._

高德地图没有这方面的扩展

**Comment by SanMu9** [comment]
好的，了解了，谢啦

**Comment by chengquan223** [comment]
> 好的，了解了，谢啦

增加了一个高德地图demo
https://chengquan223.github.io/map-canvas/examples/amap-flashmarker.html
